"""Data models for dynamic skills and Skill Auditor security policy."""

from __future__ import annotations

from collections.abc import Mapping
from enum import StrEnum
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from uclone_x.sandbox.models import IsolationLevel

__all__ = [
    "AuditVerdict",
    "AutoApprovalPolicy",
    "SkillAuditReport",
    "SkillManifest",
    "SkillOrigin",
    "SkillStatus",
]


class AutoApprovalPolicy(StrEnum):
    """Auto-approval policy for synthesized skills (P9 / FR-5.4)."""

    ALWAYS = "always"
    SAFE_ONLY = "safe_only"
    NEVER = "never"


class SkillOrigin(StrEnum):
    """Who wrote a skill.

    The distinction is load-bearing: review finding 2026-09-02-002 turns on the fact that
    a synthesized skill is code an LLM authored, and the runtime must be able to tell
    the two apart without inferring it from a directory name. (The Markdown findings
    register that held it is retired; the snapshot survives as an eval fixture.)
    """

    HUMAN = "human"
    SYNTHESIZED = "synthesized"


class SkillStatus(StrEnum):
    """Where a skill sits in the promotion lifecycle.

    `PENDING` is the quarantine state issue 2026-09-02-002 requires: a synthesized
    package exists on disk but is not loadable by any agent until something promotes it.
    """

    PENDING = "pending"
    ACTIVE = "active"
    QUARANTINED = "quarantined"
    REJECTED = "rejected"


class AuditVerdict(StrEnum):
    """The auditor's recommendation. A closed set, so an unknown verdict cannot pass."""

    APPROVE = "approve"
    REQUIRE_HUMAN_REVIEW = "require_human_review"
    REJECT = "reject"


class SkillManifest(BaseModel):
    """Metadata extracted from SKILL.md frontmatter, plus runtime provenance."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    name: str
    description: str
    version: str = "0.1.0"
    author: str | None = None
    scripts: tuple[str, ...] = Field(default_factory=tuple)
    tags: tuple[str, ...] = Field(default_factory=tuple)
    entrypoint: str | None = None
    origin: SkillOrigin = Field(
        description="Required. A skill that cannot say who wrote it cannot be governed.",
    )
    status: SkillStatus = Field(
        default=SkillStatus.PENDING,
        description="Defaults to quarantine, so a package is inert until promoted.",
    )
    requested_isolation: IsolationLevel | None = Field(
        default=None,
        description="What the SKILL.md asked for. Advisory only: per issue "
        "2026-09-02-002 the runtime decides the ceiling, because an agent that writes "
        "its own manifest would otherwise grant itself host execution.",
    )
    content_sha256: str | None = Field(
        default=None,
        description="Digest of the package contents at audit time, so a later edit is "
        "detectable and an audit cannot be inherited by different code.",
    )
    approved_by: str | None = Field(
        default=None,
        description="Identifier of the human or process that approved this skill.",
    )
    approved_at: str | None = Field(
        default=None,
        description="UTC ISO-8601 timestamp when this skill was approved.",
    )
    rejected_by: str | None = Field(
        default=None,
        description="Identifier of the human or process that rejected this skill.",
    )
    rejected_at: str | None = Field(
        default=None,
        description="UTC ISO-8601 timestamp when this skill was rejected.",
    )
    rejection_reason: str | None = Field(
        default=None,
        description="Explanation if the skill was rejected.",
    )

    def model_copy(self, *, update: Mapping[str, Any] | None = None, deep: bool = False) -> Self:
        """Override model_copy so updates are strictly validated through model_validate (Issue #42)."""
        if update:
            dumped: dict[str, Any] = dict(self.model_dump())
            dumped.update(update)
            return type(self).model_validate(dumped)
        return super().model_copy(deep=deep)


class SkillAuditReport(BaseModel):
    """Automated security and red-teaming report generated by the Skill Auditor agent.

    The defaults fail in the safe direction. The previous shape defaulted to
    `risk_score=0.0` and `recommendation="approve"`, so an auditor that crashed, or was
    never invoked at all, produced a report reading "safe, approve" — the fail-open
    posture recorded as finding F5 in `docs/security-threat-model.md`.
    """

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    skill_name: str
    is_safe: bool = Field(
        description="Required. There is no safe default for 'is this safe'.",
    )
    recommendation: AuditVerdict = Field(
        description="Required, and a closed set: no default, so an unwritten field "
        "cannot read as approval.",
    )
    risk_score: float | None = Field(
        default=None,
        description="None until actually measured. A defaulted 0.0 is indistinguishable "
        "from 'measured and found harmless'.",
    )
    detected_risks: tuple[str, ...] = Field(default_factory=tuple)
    auditor_version: str | None = None
    content_sha256: str | None = Field(
        default=None,
        description="Digest of what was audited, so a registry can refuse a report that "
        "does not cover the code in front of it.",
    )

    @property
    def verdict(self) -> AuditVerdict:
        """Alias for recommendation for consistency with AuditVerdict naming."""
        return self.recommendation

    @model_validator(mode="after")
    def _validate_consistency(self) -> Self:
        if self.recommendation is AuditVerdict.APPROVE and not self.is_safe:
            raise ValueError("SkillAuditReport cannot recommend APPROVE when is_safe is False")
        if self.recommendation is AuditVerdict.REJECT and self.is_safe:
            raise ValueError("SkillAuditReport cannot recommend REJECT when is_safe is True")
        return self
