"""LLM-Agnostic subsystem: Multi-provider abstraction, token budgeting, and context compaction."""

from uclone_x.llm.budget import TokenBudgetManager
from uclone_x.llm.compactor import ContextCompactor
from uclone_x.llm.connectors import (
    DEFAULT_EMBEDDING_DIMENSIONS,
    DEFAULT_EMBEDDING_MODEL,
    EMBEDDING_DIMENSIONS_ENV_VAR,
    EMBEDDING_MODEL_ENV_VAR,
    AnthropicConnector,
    BaseLLMConnector,
    GeminiConnector,
    MockLLMConnector,
    OllamaConnector,
    OllamaEmbedder,
    OpenAIConnector,
    VLLMConnector,
    create_llm_connector,
    has_configured_vllm_endpoint,
    normalize_ollama_base_url,
    normalize_vllm_base_url,
    resolve_embedding_dimensions,
    resolve_embedding_model,
    resolve_ollama_base_url,
    resolve_ollama_model,
    resolve_vllm_base_url,
    resolve_vllm_model,
)
from uclone_x.llm.models import (
    BudgetDecision,
    ChatMessage,
    CompactionOutcome,
    FinishReason,
    LedgerSource,
    LLMRequest,
    MessageRole,
    ModelResponse,
    StreamChunk,
    TokenBudget,
    TokenCountSource,
    TokenUsage,
    ToolCallRequest,
    ToolDefinition,
)
from uclone_x.llm.protocols import (
    ContextCompactorProtocol,
    EmbedderProtocol,
    LLMProviderProtocol,
    TokenBudgetManagerProtocol,
)

__all__ = [
    "AnthropicConnector",
    "BaseLLMConnector",
    "BudgetDecision",
    "ChatMessage",
    "CompactionOutcome",
    "ContextCompactor",
    "ContextCompactorProtocol",
    "DEFAULT_EMBEDDING_DIMENSIONS",
    "DEFAULT_EMBEDDING_MODEL",
    "EMBEDDING_DIMENSIONS_ENV_VAR",
    "EMBEDDING_MODEL_ENV_VAR",
    "EmbedderProtocol",
    "FinishReason",
    "GeminiConnector",
    "LLMProviderProtocol",
    "LLMRequest",
    "LedgerSource",
    "MessageRole",
    "MockLLMConnector",
    "ModelResponse",
    "OllamaConnector",
    "OllamaEmbedder",
    "OpenAIConnector",
    "VLLMConnector",
    "StreamChunk",
    "TokenBudget",
    "TokenBudgetManager",
    "TokenBudgetManagerProtocol",
    "TokenCountSource",
    "TokenUsage",
    "ToolCallRequest",
    "ToolDefinition",
    "create_llm_connector",
    "has_configured_vllm_endpoint",
    "normalize_ollama_base_url",
    "normalize_vllm_base_url",
    "resolve_embedding_dimensions",
    "resolve_embedding_model",
    "resolve_ollama_base_url",
    "resolve_ollama_model",
    "resolve_vllm_base_url",
    "resolve_vllm_model",
]
