"""Ontology subsystem: LinkML domain schemas, Tier-1 validation, and autonomous induction."""

from uclone_x.ontology.engine import (
    ExpressionEvaluationError,
    OntologyEngine,
    OntologyInducer,
    OntologyService,
    SessionKnowledgeExtractor,
    safe_eval_rule_expression,
)
from uclone_x.ontology.justification import (
    TYPE_PREDICATE,
    Closure,
    Fact,
    Inconsistency,
    ProofStep,
    UnsupportedAxiom,
    compute_fact_id,
)
from uclone_x.ontology.models import (
    EntitySchema,
    EvidenceRecord,
    InvariantSchema,
    OntologyAxiom,
    OntologyConcept,
    OntologyInvariant,
    OntologyRelation,
    OntologyTier,
    OntologyValidationResult,
    RelationSchema,
    ValidationResult,
    compute_axiom_hash,
    compute_concept_hash,
    compute_relation_hash,
)
from uclone_x.ontology.protocols import (
    OntologyEngineProtocol,
    OntologyInducerProtocol,
    OntologyServiceProtocol,
    OntologyValidatorProtocol,
)
from uclone_x.ontology.reasoner import OntologyReasoner, check_consistency, materialize

__all__ = [
    "Closure",
    "EntitySchema",
    "EvidenceRecord",
    "ExpressionEvaluationError",
    "Fact",
    "Inconsistency",
    "InvariantSchema",
    "OntologyAxiom",
    "OntologyConcept",
    "OntologyEngine",
    "OntologyEngineProtocol",
    "OntologyInducer",
    "OntologyInducerProtocol",
    "OntologyInvariant",
    "OntologyReasoner",
    "OntologyRelation",
    "OntologyService",
    "OntologyServiceProtocol",
    "OntologyTier",
    "OntologyValidationResult",
    "OntologyValidatorProtocol",
    "ProofStep",
    "RelationSchema",
    "SessionKnowledgeExtractor",
    "TYPE_PREDICATE",
    "UnsupportedAxiom",
    "ValidationResult",
    "check_consistency",
    "compute_axiom_hash",
    "compute_concept_hash",
    "compute_fact_id",
    "compute_relation_hash",
    "materialize",
    "safe_eval_rule_expression",
]
